/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getHandler(code: string, id: string, walnutKey: string): WalnutHandler
export function resolveDependencies(base: string, entry: string): void
export class WalnutHandler {
  needResolver: boolean
  run(): void
  getOutput(): string
  getResolverLabels(): Array<string>
  satisfyResolvers(resolverArr: Array<[string, string]>): void
}
